name: CI-CD Pipeline

on:
  push:
    branches:
      - dev
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET 9 SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Run tests
      run: dotnet test --no-build --verbosity normal

    - name: Checkout master branch
      run: git checkout master
      
    - name: Merge dev into master
      run: |
       git config user.name "${{ secrets.DOCKER_USERNAME }}"
       git config user.email "${{ secrets.GIT_USER_EMAIL }}"
        git fetch origin dev
        git merge origin/dev --no-ff --no-commit || (echo "Merge conflict detected. Aborting." && exit 1)
        git commit -m "Auto-merged dev into master [skip ci]" || echo "Nothing to commit"
        git push origin master


    - name: Build CatalogService Docker image
      working-directory: ./CatalogService
      run: docker build -t soumyatajena/catalogservice:latest .

    - name: Build OrderService Docker image
      working-directory: ./OrderService
      run: docker build -t soumyatajena/orderservice:latest .

    - name: Build AuthService Docker image
      working-directory: ./AuthService
      run: docker build -t soumyatajena/authservice:latest .

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push CatalogService Docker image
      run: docker push soumyatajena/catalogservice:latest

    - name: Push OrderService Docker image
      run: docker push soumyatajena/orderservice:latest

    - name: Push AuthService Docker image
      run: docker push soumyatajena/authservice:latest
